In [1]:
# import Python libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load dataset
url = "http://bit.ly/FinancialDataset"

finData = pd.read_csv(url)
finData.head()

,country,year,uniqueid,Has a Bank account,Type of Location,Cell Phone Access,household_size,Respondent Age,gender_of_respondent,The relathip with head,marital_status,Level of Educuation,Type of Job
0,Kenya,2018,uniqueid_1,Yes,Rural,Yes,3.0,24.0,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,No,Rural,No,5.0,70.0,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,Yes,Urban,Yes,5.0,26.0,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,No,Rural,Yes,5.0,34.0,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,No,Urban,No,8.0,26.0,Male,Child,Single/Never Married,Primary education,Informally employed

In [13]:
# check shape of dataset
finData.shape

(23524, 13)

In [7]:
# check for duplicates
finData.duplicated()

# display duplicates, if any
duplicatedData = finData[finData.duplicated()]
print(duplicatedData)

Empty DataFrame
Columns: [country, year, uniqueid, Has a Bank account, Type of Location, Cell Phone Access, household_size, Respondent Age, gender_of_respondent, The relathip with head, marital_status, Level of Educuation, Type of Job]
Index: []

In [19]:
# check for missing data
print(finData.isnull().sum())

# store rows with empty values
nullValues = finData[finData.isna().any(axis=1)]

country                   14
year                       0
uniqueid                   0
Has a Bank account        36
Type of Location          15
Cell Phone Access         11
household_size            28
Respondent Age            34
gender_of_respondent      34
The relathip with head     4
marital_status            32
Level of Educuation       29
Type of Job               30
dtype: int64

In [20]:
# create Kenyan Dataset and save to CSV
finKE = finData.loc[finData['country'] == 'Kenya']
finKE.to_csv('finKE.csv', index=False)

,country,year,uniqueid,Has a Bank account,Type of Location,Cell Phone Access,household_size,Respondent Age,gender_of_respondent,The relathip with head,marital_status,Level of Educuation,Type of Job
0,Kenya,2018,uniqueid_1,Yes,Rural,Yes,3.0,24.0,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,No,Rural,No,5.0,70.0,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,Yes,Urban,Yes,5.0,26.0,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,No,Rural,Yes,5.0,34.0,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,No,Urban,No,8.0,26.0,Male,Child,Single/Never Married,Primary education,Informally employed
5,Kenya,2018,uniqueid_6,No,Rural,No,7.0,26.0,Female,Spouse,Married/Living together,Primary education,Informally employed
6,Kenya,2018,uniqueid_7,No,Rural,Yes,7.0,32.0,Female,Spouse,Married/Living together,Primary education,Self employed
7,Kenya,2018,uniqueid_8,No,Rural,Yes,1.0,42.0,Female,Head of Household,Married/Living together,Tertiary education,Formally employed Government
8,Kenya,2018,uniqueid_9,Yes,Rural,Yes,3.0,54.0,Male,Head of Household,Married/Living together,Secondary education,Farming and Fishing
9,Kenya,2018,uniqueid_10,No,Urban,Yes,3.0,76.0,Female,Head of Household,Divorced/Seperated,No formal education,Remittance Dependent
10,Kenya,2018,uniqueid_11,No,Rural,Yes,5.0,40.0,Female,Head of Household,Married/Living together,Secondary education,Farming and Fishing
11,Kenya,2018,uniqueid_12,Yes,Rural,Yes,3.0,69.0,Male,Head of Household,Married/Living together,Secondary education,Other Income
12,Kenya,2018,uniqueid_13,No,Rural,No,6.0,64.0,Female,Head of Household,Widowed,No formal education,Farming and Fishing
13,Kenya,2018,uniqueid_14,No,Rural,No,8.0,31.0,Female,Spouse,Married/Living together,Primary education,Self employed
14,Kenya,2018,uniqueid_15,No,Urban,Yes,4.0,26.0,Male,Head of Household,Married/Living together,Primary education,Informally employed
15,Kenya,2018,uniqueid_16,No,Rural,Yes,7.0,38.0,Male,Head of Household,Married/Living together,Primary education,Informally employed
16,Kenya,2018,uniqueid_17,No,Urban,Yes,1.0,47.0,Female,Head of Household,Married/Living together,Secondary education,Self employed
17,Kenya,2018,uniqueid_18,Yes,Rural,Yes,6.0,27.0,Female,Head of Household,Married/Living together,Secondary education,Self employed
18,Kenya,2018,uniqueid_19,No,Urban,Yes,1.0,48.0,Female,Head of Household,Single/Never Married,Vocational/Specialised training,Formally employed Private
19,Kenya,2018,uniqueid_20,No,Rural,No,4.0,25.0,Female,Spouse,Married/Living together,Primary education,Farming and Fishing
20,Kenya,2018,uniqueid_21,No,Rural,Yes,4.0,26.0,Male,Head of Household,Married/Living together,Primary education,Farming and Fishing
21,Kenya,2018,uniqueid_22,Yes,Urban,Yes,1.0,32.0,Male,Head of Household,Single/Never Married,Vocational/Specialised training,Self employed
22,Kenya,2018,uniqueid_23,No,Urban,Yes,4.0,34.0,Female,Spouse,Married/Living together,Secondary education,Self employed
23,Kenya,2018,uniqueid_24,No,Rural,Yes,3.0,21.0,Female,Spouse,Married/Living together,Secondary education,Informally employed
24,Kenya,2018,uniqueid_25,No,Urban,No,7.0,18.0,Male,Other relative,Single/Never Married,Secondary education,Remittance Dependent
25,Kenya,2018,uniqueid_26,No,Rural,Yes,5.0,22.0,Female,Child,Single/Never Married,Secondary education,Remittance Dependent
26,Kenya,2018,uniqueid_27,No,Rural,No,8.0,26.0,Male,Child,Married/Living together,Primary education,Self employed
27,Kenya,2018,uniqueid_28,No,Urban,Yes,1.0,31.0,Female,Head of Household,Single/Never Married,Primary education,Informally employed
28,Kenya,2018,uniqueid_29,No,Rural,Yes,4.0,26.0,Male,Head of Household,Married/Living together,Primary education,Formally employed Private
29,Kenya,2018,uniqueid_30,No,Rural,No,7.0,58.0,Female,Head of Household,Widowed,No formal education,Remittance Dependent
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6038,Kenya,2018,uniqueid_6039,No,Rural,Yes,7.0,30.0,Female,Head of Household,Married/Living together,Primary education,Remittance Dependent
6039,Kenya,2018,uniqueid_6040,No,Rural,Yes,6.0,51.0,Male,Head of Household,Divorced/Seperated,No formal education,Farming and Fishing
6040,Kenya,2018,uniqueid_6041,Yes,Urban,Yes,4.0,32.0,Male,Head of Household,Married/Living together,Secondary education,Formally employed Private
6041,Kenya,2018,uniqueid_6042,No,Rural,Yes,6.0,41.0,Male,Head of Household,Married/Living together,Secondary education,Farming and Fishing
6042,Kenya,2018,uniqueid_6043,No,Rural,Yes,5.0,28.0,Female,Spouse,Married/Living together,Primary education,Informally employed
6043,Kenya,2018,uniqueid_6044,No,Rural,Yes,8.0,18.0,Male,Child,Single/Never Married,Secondary education,Farming and Fishing
6044,Kenya,2018,uniqueid_6045,No,Rural,Yes,5.0,74.0,Female,Head of Household,Widowed,Primary education,Remittance Dependent
6045,Kenya,2018,uniqueid_6046,No,Urban,Yes,1.0,21.0,Female,Head of Household,Single/Never Married,Secondary education,Informally employed
6046,Kenya,2018,uniqueid_6047,Yes,Urban,Yes,6.0,44.0,Female,Spouse,Married/Living together,Tertiary education,Self employed
6047,Kenya,2018,uniqueid_6048,No,Urban,No,1.0,38.0,Male,Head of Household,Divorced/Seperated,Primary education,Informally employed
6048,Kenya,2018,uniqueid_6049,No,Rural,Yes,5.0,18.0,Male,Child,Single/Never Married,Primary education,Informally employed
6049,Kenya,2018,uniqueid_6050,No,Urban,Yes,3.0,28.0,Female,Head of Household,Married/Living together,Primary education,Remittance Dependent
6050,Kenya,2018,uniqueid_6051,Yes,Urban,Yes,4.0,42.0,Male,Head of Household,Married/Living together,Vocational/Specialised training,Formally employed Private
6051,Kenya,2018,uniqueid_6052,No,Urban,Yes,12.0,22.0,Female,Child,Single/Never Married,No formal education,Remittance Dependent
6052,Kenya,2018,uniqueid_6053,No,Urban,No,5.0,27.0,Female,Spouse,Married/Living together,Primary education,Remittance Dependent
6053,Kenya,2018,uniqueid_6054,No,Urban,Yes,3.0,22.0,Male,Head of Household,Married/Living together,Primary education,Formally employed Private
6054,Kenya,2018,uniqueid_6055,No,Rural,Yes,4.0,20.0,Female,Other relative,Single/Never Married,Secondary education,Farming and Fishing
6055,Kenya,2018,uniqueid_6057,No,Rural,Yes,5.0,57.0,Male,Head of Household,Married/Living together,Primary education,Informally employed
6056,Kenya,2018,uniqueid_6058,No,Rural,No,7.0,30.0,Male,Head of Household,Married/Living together,Primary education,Informally employed
6057,Kenya,2018,uniqueid_6059,No,Rural,No,5.0,60.0,Female,Spouse,Married/Living together,Secondary education,Farming and Fishing
6058,Kenya,2018,uniqueid_6061,No,Urban,Yes,3.0,73.0,Female,Head of Household,Widowed,Primary education,Farming and Fishing
6059,Kenya,2018,uniqueid_6062,No,Rural,Yes,1.0,70.0,Male,Head of Household,Widowed,No formal education,Farming and Fishing
6060,Kenya,2018,uniqueid_6063,No,Urban,Yes,1.0,55.0,Male,Head of Household,Married/Living together,Secondary education,Informally employed
6061,Kenya,2018,uniqueid_6064,No,Urban,Yes,4.0,40.0,Female,Head of Household,Divorced/Seperated,Secondary education,Formally employed Government
6062,Kenya,2018,uniqueid_6066,No,Rural,No,1.0,17.0,Male,Head of Household,Single/Never Married,Primary education,Informally employed
6063,Kenya,2018,uniqueid_6067,No,Rural,Yes,4.0,26.0,Female,Head of Household,Married/Living together,Primary education,Remittance Dependent
6064,Kenya,2018,uniqueid_6068,No,Urban,No,5.0,17.0,Female,Child,Single/Never Married,Secondary education,Remittance Dependent
6065,Kenya,2018,uniqueid_6069,No,Rural,Yes,9.0,30.0,Female,Spouse,Married/Living together,No formal education,Farming and Fishing
6066,Kenya,2018,uniqueid_6070,No,Rural,Yes,3.0,52.0,Male,Head of Household,Married/Living together,Primary education,Self employed
6067,Kenya,2018,uniqueid_6071,No,Rural,Yes,2.0,75.0,Female,Spouse,Married/Living together,Primary education,Farming and Fishing

In [14]:
# create Tanzanian Dataset and save to CSV
finTZ = finData.loc[finData['country'] == 'Tanzania']
finTZ.to_csv('finTZ.csv', index=False)

(6606, 13)

In [15]:
# create Ugandan Dataset and save to CSV
finUG = finData.loc[finData['country'] == 'Uganda']
finUG.to_csv('finE.csv', index=False)

(2101, 13)

In [16]:
# create Rwandan Dataset and save to CSV
finRW = finData.loc[finData['country'] == 'Rwanda']
finRW.shape

(8735, 13)